### ISSUE TITLE
Either embedded in stream

### ISSUE THREAD

**Issue by goodmind** [TylorS/typed-stream#1]
It would be good if  we had `Stream<A, B>` type like Fluture library but for streams

**Comment by goodmind** [comment]
https://github.com/fluture-js/Fluture

**Comment by Frikki** [comment]
What's the use case?

**Comment by TylorS** [comment]
Hello @goodmind, currently this library isn't trying to _implement_ a `Stream` library but only be an extension to [`@most/core`](https://github.com/mostjs/core) which already has a `Stream<A>` type. I think this discussion would be best had there, and could be welcomed addition as we're already working on a number of breaking changes.

Also just as an FYI [`@typed/future`](https://github.com/TylorS/typed/tree/master/packages/future) is a future library I've made.

**Comment by goodmind** [comment]
@TylorS Hello, not just `Stream<A>` but `Stream<A, B>` with error type

**Comment by TylorS** [comment]
I think this question would be better directed toward the most team. As such I've just opened https://github.com/mostjs/core/issues/145
