### ISSUE TITLE
Fix published package

### ISSUE THREAD

**Issue by Frikki** [TylorS/typed-stream#16]
**Code to reproduce the issue:**

```sh
yarn add @typed/stream
# or
npm install --save @typed/stream
```

**Expected behavior:**

Installs and adds `@typed/stream` to npm dependencies.

**Actual behavior:**

Using yarn:
```sh
error An unexpected error occurred: "https://registry.yarnpkg.com/@typed%2fstream: Not found".
```

Using npm:
```sh
npm ERR! code E404
npm ERR! 404 Not Found: @typed/stream@latest
```

**Versions of packages used:**

Yarn v1.3.0-20171101.1634
npm v5.3.0

**Comment by TylorS** [comment]
Hehe, it's not published yet. I'll do it soon.

**Comment by TylorS** [comment]
Published now!
