### ISSUE TITLE
Re-export fromFuture in top-level index.ts

### ISSUE THREAD

**Issue by Frikki** [TylorS/typed-stream#21]
**Code to reproduce the issue:**

```ts
import { fromFuture } from '@typed/stream'
```

**Expected behavior:**

`fromFuture` is imported.

**Actual behavior:**

```sh
[ts] Module '"./node_modules/@typed/stream/lib/index"' has no exported member 'fromFuture'.
```

**Versions of packages used:**

`@typed/stream@1.0.0`

**Comment by TylorS** [comment]
Thanks for the issue

**Comment by Frikki** [comment]
I’m closing this issue since the request was implemented in this commit: https://github.com/TylorS/typed-stream/commit/e28179c5ad38324ba7862e43b92d2088cf8ec7bf#diff-f41e9d04a45c83f3b6f6e630f10117feR2
